site_name: WinuxCommands
repo_url: https://github.com/Zalgo-Dev/WinuxCommands
theme:
  name: dracula
nav:
  - Accueil: index.md
  - Installation: installation.md
  - Commandes disponibles: commandes.md
  - Contribution: contribution.md
extra_css:
  - css/custom.css